version: 2.1
orbs:
  cypress: cypress-io/cypress@2
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  Build:
      jobs:
        - cypress/install
        - cypress/run:
            requires:
              - cypress/install
            record: true
            executor: with-chrome
            browser: chrome
            spec: cypress/e2e/*
            parallel: true
            parallelism: 4
          

            